### ISSUE TITLE
•	Mapping tiles still need to be moved to the richer content layer with street numbers, and so forth

### ISSUE THREAD

**Issue by polysteve** [3DXScape/MobileLocater#11]
Apparently the new rendering style is OK so it should be applied to all static tiles in CT

**Comment by polysteve** [comment]
All tiles updated to new style

**Comment by 3DXScape** [comment]
I will increase the street name density.

**Comment by nickholly** [comment]
Are house number details available?

**Comment by polysteve** [comment]
Adding house numbers to the issue. I think we can put house numbers in many of the parcel polygons and it may be possible to place them at each street crossing.

**Comment by 3DXScape** [comment]
Final map accepted
