### ISSUE TITLE
Nearest cross street function is not yet available

### ISSUE THREAD

**Issue by polysteve** [3DXScape/MobileLocater#13]
#### Expected: Get address and nearest cross street using following algorithm:
1. `Prepare a set of candidate service address streets by clipping all the streets in the world against the geometry
2.  If candidate service address street set is empty, return town, state
3.  The service address street is the member of candidate service address streets set with the longest geometry
4.  Prepare a candidate intersection geometry by subtracting the part of the original service address street geometry that lies within the geometry
5.  Prepare a set of candidate cross streets by eliminating all streets in the world that do not intersect the candidate intersection geometry
6.  If the candidate cross streets set is empty (for example, disconnected segments or closed loops),  then return town, state 
7.  Return the candidate cross street whose first intersection outside the geometry is the nearest to the geometry.

**Comment by 3DXScape** [comment]
Implemented as described.
