### ISSUE TITLE
Addresses that come out at the wrong spot

### ISSUE THREAD

**Issue by polysteve** [3DXScape/MobileLocater#16]

**Comment by hellokarl** [comment]
If you perform a search for washington ave, hamden, it takes you to X: -72.85696, Y: 41.40351

This is nowhere near the correct address (41.387227, -72.897933)

**Comment by hellokarl** [comment]
[error with mapping for USA.docx](https://github.com/polysteve/MobileLocater/files/46865/error.with.mapping.for.USA.docx)

Dixwell Ave Hamden CT. Did not take me to the street.
Whitney Avenue Hamden Ct. Did not take me to Whitney Ave.

**Comment by 3DXScape** [comment]
This issue is the same as issue 25.
