### ISSUE TITLE
Tile details sparse

### ISSUE THREAD

**Issue by hellokarl** [3DXScape/MobileLocater#18]
New hamden tiles are still very sparse
![capture](https://cloud.githubusercontent.com/assets/16073472/11488948/f4d5e5ca-981e-11e5-87cd-fb17f1cfd3e0.PNG)

**Comment by 3DXScape** [comment]
New map has all streets named, larger labels, town line

![2040whitneynewmap](https://cloud.githubusercontent.com/assets/4260590/11900753/b7506284-a55c-11e5-8c0d-14b9d9d522b4.PNG)
