### ISSUE TITLE
Location of found intersection (Gill

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#20]
![intersection location wrong](https://cloud.githubusercontent.com/assets/16123724/11542026/677cbf24-9903-11e5-9723-fefd8abf5c36.PNG)

The location found for the intersection search performed is incorrect.

**Comment by polysteve** [comment]
Nick
Karl got me onto the test system so I can check these directly now. - I don't have any new info yet but I can reproduce your results

**Comment by 3DXScape** [comment]
Fixed

![gillies-edgemere](https://cloud.githubusercontent.com/assets/4260590/11709670/373b7f78-9ece-11e5-8112-e6272f13e32f.PNG)
