### ISSUE TITLE
Street Search Issues

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#21]
595 deercliff rd avon   didnt find street
480 flatbush ave hartford   location search failed
bishop st state hwy 15 north haven  location search failed
63 west ave norwalk address not found
53 main st  meriden 300ft away from location
old ridgebury rd danbury    not found
reserve rd danbury  not found
union carbide rd danbury    not found
coonors ln/knollwood dr stratford   2 inters,querries in middle
78 longmeadow rd hamden not found blue map
26-27 hill rd east lyme in our maping this street name apears in 3 differnet locs will not populate on this map 
159 Borrmann rd, East Haven location search failed
Willow Rd/State Hwy 80, East Haven  location search failed
35 Wheelbarrow Ln, East Haven   location search failed
16 State St, North Haven    mapping alignment issue - aprx 500ft away from actual address

**Comment by nickholly** [comment]
![image](https://cloud.githubusercontent.com/assets/16123724/11638901/5ab42a3c-9cf7-11e5-976c-c246a2a3b8ba.png)

**Comment by 3DXScape** [comment]
Working through these by using new CBYD application and examining log files to trace process. Many (most?) seem to work as expected as of 7 December. 

There is an existing issue on making the representative point match the parcel rather than the containing block that should address mapping alignment

**Comment by 3DXScape** [comment]
The representative point as well as the returned geometry have moved to the best estimate of the true location of the address. There is a remaining issue with limited access roads where crossing roads do not actually intersect the lanes of the limited access road (expressways, parkways, interstates). For location purposes it is useful to create artificial "intersections" where the roadways cross even if they are not joined.

**Comment by 3DXScape** [comment]
Physical intersections are the remaining match issue - that is covered by  issue 19. so this one is fixed.

**Comment by nickholly** [comment]
Thanks Steve we will retest and confirm.
