### ISSUE TITLE
Addresses not found in West Hartford

### ISSUE THREAD

**Issue by hellokarl** [3DXScape/MobileLocater#24]
Address (Cross street)

All of the following addresses are in WEST HARTFORD: 

1678 ASYLUM AVENUE (Trout Brook DR)
15 FAXON DRIVE (Lovelace DR) [did find address in Hartford]
49 FAIRVIEW STREET (S Highland ST)
52 KANE ST (Prospect AVE)
61 FLAGG RD (Blue Ridge LN)
QUAKER LANE S / EXETER AVENUE
QUAKER LANE S / CAROL ROAD
39 GREYSTONE ROAD (Overbrook RD)
1253 NEW BRITAIN AVENUE (S Main ST)
160 MOHEGAN DRIVE (Parsons DR)

1232 STORRS RD (S Eagleville Rd) [Mansfield, CT] <--- I did find this as an intersection but could not locate with the address. 

I did try to locate all of these addresses without the numbers, and changing the city to Hartford. I also tried to locate them as intersections in both West Hartford and Hartford. Mansfield address was the only other one I had trouble locating. Out of the hundred or so tickets I entered into the MAPPING area, West Hartford and Mansfield were the only ones I had trouble with. I am in search for more tickets for Mansfield to test if they work or not. That just happened to be the only one in the stack I took home to enter. 

There was a glitch I ran into while doing this. While I was entering addresses into the "STREET" search, I switched to "INTERSECTION". When I tired to go back to the "STREET" it disappeared and showed two "INTERSECTION" fields. See attached screen shot. This was being done on my personal laptop (Macbook Pro) using Google Chrome browser. 

I will continue to enter addresses into the system.

Feel free to respond with any questions you may have.  
Anthony R. Willemain

Centre Manager

PelicanCorp

**Comment by 3DXScape** [comment]
I am having trouble reproducing this. We must not be testing the same way. I attached some samples. Still investigating.
![15faxondrwesthartfordct](https://cloud.githubusercontent.com/assets/4260590/11920664/9401bef2-a72a-11e5-97fb-7cc6528e9387.png)
![52kanestwesthartfordct](https://cloud.githubusercontent.com/assets/4260590/11920668/9407ea5c-a72a-11e5-8932-1fbc51fa052b.png)
![61flaggrdwesthartfordct](https://cloud.githubusercontent.com/assets/4260590/11920666/940795c0-a72a-11e5-921e-dd55a30fb57f.png)
![39greystoneroadwesthartfordct](https://cloud.githubusercontent.com/assets/4260590/11920665/9405c092-a72a-11e5-8671-65e0f9f132d1.png)
![160mohegandrivewesthartfordct](https://cloud.githubusercontent.com/assets/4260590/11920667/9407bc58-a72a-11e5-8758-07752819b8ec.png)

**Comment by 3DXScape** [comment]
Able to reproduce in Chrome: a browser dependency that caused a parse error. Code added to handle case and now tests OK here.

**Comment by 3DXScape** [comment]
Released
