### ISSUE TITLE
Intersection Austin Road and Scott Road Prospect - Not found

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#31]
[Prospect - Austin Road.pptx](https://github.com/polysteve/MobileLocater/files/70034/Prospect.-.Austin.Road.pptx)

**Comment by 3DXScape** [comment]
Reproduce: enter 70 West River St. Milford, CT 
Result: does not match
Expected: match

Cause is known and fix will be in next build. It is a parse error and will affect any address where the town name also appears as part or all of the street name - in this case "Milford"

**Comment by 3DXScape** [comment]
Further investigation shows that the cause is _not_ as above. Still checking.

**Comment by nickholly** [comment]
It appears that Prospect is not a town worth working in - or at least thats what we are trying to communicate? A number of other reports around Prospect CT attached.

[Prospect - Any Street.pptx](https://github.com/polysteve/MobileLocater/files/70130/Prospect.-.Any.Street.pptx)

**Comment by polysteve** [comment]
Believed to be fixed. Please check. Problem was a parse error but was due to "Prospect" being recognized as a street type.

**Comment by 3DXScape** [comment]
Appears fixed in latest build. Please verify.

**Comment by nickholly** [comment]
fixed.
