### ISSUE TITLE
70 West River St. Milford, CT 

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#32]
This is the Milford City offices - it cannot be found.

**Comment by nickholly** [comment]
In fact, no house number can be found along West River Street - it appears there are no address values for this site.

**Comment by polysteve** [comment]
Reproduced.
Parse error due to failure to match st as suffix vs River - pulled River from list to fix.

**Comment by nickholly** [comment]
Tested and verified - fixed.
