### ISSUE TITLE
East Main Street Waterbury - Wrong representative point

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#33]
![image](https://cloud.githubusercontent.com/assets/16123724/11962360/4238c6e0-a8ad-11e5-93a8-233256aad78e.png)

**Comment by nickholly** [comment]
The image shows the point somewhere on Homestead Road but it needs to be several hundred feet south.

**Comment by 3DXScape** [comment]
This is a case of issue 25. I copied it there.
