### ISSUE TITLE
Property Parcel Data - showing errors

### ISSUE THREAD

**Issue by nickholly** [3DXScape/MobileLocater#36]
![image](https://cloud.githubusercontent.com/assets/16123724/11983113/ec82df38-a97e-11e5-84f9-ea426e7d111b.png)

**Comment by polysteve** [comment]
Reproduced
Will adjust filter on next parcel layer build

**Comment by nickholly** [comment]
Please confirm when completed.

Nick Holly
Business Development

PelicanCorp One Call, Inc.
Software and Services for the Protection of Essential Infrastructure
2040 Whitney Ave Hamden CT 06517
(p)  (203) 230 3060
(m) (203) 859 1121
www.pelicancorp.comhttp://www.pelicancorp.com/

**Comment by 3DXScape** [comment]
Fix in test. Tiles should be rebuilt 1-2 Jan.

**Comment by nickholly** [comment]
Thank you.

Nick Holly
Business Development

PelicanCorp One Call, Inc.
Software and Services for the Protection of Essential Infrastructure
2040 Whitney Ave Hamden CT 06517
(p)  (203) 230 3060
(m) (203) 859 1121
www.pelicancorp.comhttp://www.pelicancorp.com/

**Comment by 3DXScape** [comment]
After the build, there are still some areas that need fixes - ETA now 5 January.

**Comment by 3DXScape** [comment]
Appears fixed. Please check.
![witches](https://cloud.githubusercontent.com/assets/4260590/12136005/32077c98-b3f8-11e5-87d7-6881644b52e6.PNG)
