### ISSUE TITLE
HARTFORD - Cross streets

### ISSUE THREAD

**Issue by HelloMrWillemain** [3DXScape/MobileLocater#49]
Seems that the city of Hartford is not populating cross streets correctly. Every ticket I have looked at from the past two days are populating parallel streets as the cross streets. Please look at this issue ASAP. High Priority! See Google map screen shot where St. Monica's street in reference to Rosemont St.and Berkeley Dr to Durham St.
[20161001392.PDF](https://github.com/polysteve/MobileLocater/files/167197/20161001392.PDF)
[20161000766.PDF](https://github.com/polysteve/MobileLocater/files/167198/20161000766.PDF)
![40 rosemont st hartford](https://cloud.githubusercontent.com/assets/17441865/13670983/1f88734e-e69b-11e5-9a31-df06a5687070.PNG)
![durham st - berkely dr](https://cloud.githubusercontent.com/assets/17441865/13671062/a03c209e-e69b-11e5-957b-1cb032f4c1e8.PNG)

**Comment by HelloMrWillemain** [comment]
This is an issue on e

**Comment by 3DXScape** [comment]
This issue and the related "cross street is the same street as the dig street" require that the dig address as entered in the form be passed to the service. Our solution will be to add a parameter to the MatchCollection and ConflictCollection services for this purpose. We will implement it and then supply the information needed to implement it. The expected time is Monday US/Tuesday in Melbourne.
