### ISSUE TITLE
POCAHONTAS DR Crossstreet

### ISSUE THREAD

**Issue by HelloMrWillemain** [3DXScape/MobileLocater#67]
Ticket 20161702838 is for 69 Pocahontas DR in WEST HARTFORD. The cross street that was put onto the ticket was Brownleigh RD. Where the area is marked on the map included a cross street Hilldale RD. 

Why did the system not generate Hilldale RD instead of Brownleigh?
![pocahontas dr ticket](https://cloud.githubusercontent.com/assets/17441865/14857814/994c1492-0c6b-11e6-8a82-815f0ffe535d.PNG)
![pocahontas dr gif](https://cloud.githubusercontent.com/assets/17441865/14857855/bcd64d74-0c6b-11e6-8320-933ae3d77fa4.PNG)
![pocahontas dr](https://cloud.githubusercontent.com/assets/17441865/14857854/bcd0e7d0-0c6b-11e6-88e4-fe691411e11c.PNG)

**Comment by polysteve** [comment]
To be re-reviewed
