### ISSUE TITLE
Incorrect Property # on Map

### ISSUE THREAD

**Issue by HelloMrWillemain** [3DXScape/MobileLocater#68]
A web user called in to the center yesterday concerned the mapping address is not correct. The address of his dig site is 6 Riding Stable Trail, STAMFORD. The area indicated on the map is correct. Google maps confirms that, but the CBYD map shows the address as 3127.

3127 is the property opposite side of the road on High Ridge Road. Can we look into this area and correct the property numbers?

[6 Riding Stable Trail STAMFORD.pdf](https://github.com/polysteve/MobileLocater/files/268126/6.Riding.Stable.Trail.STAMFORD.pdf)

**Comment by polysteve** [comment]
To be re-reviewed
