### ISSUE TITLE
12 Dickenson Dr, Newtown

### ISSUE THREAD

**Issue by twigz13** [3DXScape/MobileLocater#69]
I'm getting some strange behavior with this address.
On Production I can search for "12 Dickenson Dr, Newtown" successfully, but the Suburb field fails validation.
On staging I cannot find "12 Dickenson Dr, Newtown" however "12 Dickenson Dr Newtown" works correctly, and there is no issue with the validation of the suburb.

When I switched staging to point to the Prod version of the Polytope URL, it behaved as Prod does

**Comment by polysteve** [comment]
To be re-reviewed
