### ISSUE TITLE
NO DATA ADDRESS - West Haven

### ISSUE THREAD

**Issue by HelloMrWillemain** [3DXScape/MobileLocater#71]
200 Oak St. WEST HAVEN locates a NO DATA area. The address is also a suggested address. Operator looked up intersection of Oak St/ Palace to find the address location. 
![image](https://cloud.githubusercontent.com/assets/17441865/17001170/e427c96a-4e93-11e6-821c-2f7647016871.png)
![image](https://cloud.githubusercontent.com/assets/17441865/17001326/91e680be-4e94-11e6-8a11-89ba5cbf6820.png)
![image](https://cloud.githubusercontent.com/assets/17441865/17001218/1b125cba-4e94-11e6-9fef-ba089d37f255.png)

**Comment by polysteve** [comment]
Closed
