### ISSUE TITLE
EAST LYME - Pulls wrong area for address

### ISSUE THREAD

**Issue by HelloMrWillemain** [3DXScape/MobileLocater#72]
Enter address 230 Flanders Rd EAST LYME and it find Chesterfield Rd/ Boston Post Rd near Flanders Elementary school. Can we look into why the address is pulling to a property called "Flanders" and not the actual address it should be finding? Note: Chesterfield Rd does turn into Flanders Rd south of Boston Post Rd. 
![image](https://cloud.githubusercontent.com/assets/17441865/17103579/02ccb9a4-524d-11e6-8b42-9651025c89f1.png)
![image](https://cloud.githubusercontent.com/assets/17441865/17103663/69f40fd8-524d-11e6-9e33-53b9d1c1960a.png)

**Comment by 3DXScape** [comment]
I have more or less worked out what's going on here but have not yet deployed a fix. It is a name confusion more or less as described above.

**Comment by polysteve** [comment]
Fixed
